name: Mise à jour quotidienne des prix

on:
  schedule:
    - cron: '0 11 * * 1-5'  # 20h FR
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}  # Ton PAT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install yfinance tiingo pandas sqlalchemy

   - name: Run pipeline
  env:
    TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
    DB_URL: ${{ secrets.DB_URL }}  # ← Ajoute cette ligne
  run: python stock_pipeline.py
